### ISSUE TITLE
Failed resolution of: Landroid/support/media/ExifInterface

### ISSUE THREAD

**Issue by xupangpang** [FinalTeam/RxGalleryFinal#206]
进入相册就报这个错误：
![image](https://user-images.githubusercontent.com/4363542/30708181-7bdb04d2-9f30-11e7-860b-fde06fcc6fa9.png)

**Comment by sheep0704** [comment]
是不是缺少什么引用

**Comment by sheep0704** [comment]
nocalssdeffounderror:failed resolution of :android.support.media.exifinterface.
android 5.0 -》 ExifInterface
看下sdk版本什么的

**Comment by PillarChen** [comment]
Demo测试没问题，引用到项目中多选时点击图片或者预览按钮就闪退，什么原因导致的?报错信息:
java.lang.VerifyError: Verifier rejected class cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter due to bad method android.view.View cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter.getView(int, android.view.View, android.view.ViewGroup) (declaration of 'cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter' appears in /data/app/com.manyiaby-1/split_lib_dependencies_apk.apk:classes37.dex)
11-30 15:49:43.153 31897-31897/com.manyiaby W/System.err:     at cn.finalteam.rxgalleryfinal.ui.fragment.MediaPageFragment.onViewCreatedOk(MediaPageFragment.java:94)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at cn.finalteam.rxgalleryfinal.ui.fragment.BaseFragment.onViewCreated(BaseFragment.java:64)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.os.Looper.loop(Looper.java:159)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5671)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ta/utdid2/android/utils/StringUtils;
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at com.ut.mini.crashhandler.a.a(UTExceptionParser.java:52)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at com.ut.mini.crashhandler.b.uncaughtException(UTMiniCrashHandler.java:84)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at com.tencent.bugly.crashreport.crash.e.a(BUGLY:354)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at com.tencent.bugly.crashreport.crash.e.uncaughtException(BUGLY:372)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ta.utdid2.android.utils.StringUtils" on path: DexPathList[[zip file "/data/app/com.manyiaby-1/base.apk", zip file "/data/app/com.manyiaby-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.manyiaby-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.manyiaby-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.manyiaby-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.manyiaby-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.manyiaby-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.manyiaby-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.manyiaby-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.manyiaby-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.manyiaby-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.manyiaby-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.manyiaby-1/lib/arm, /vendor/lib, /system/lib]]
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err: 	... 6 more
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.ta.utdid2.android.utils.StringUtils
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at java.lang.Class.classForName(Native Method)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err: 		... 7 more
11-30 15:49:43.163 31897-31897/com.manyiaby W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
